name: Docs Quality

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markdownlint
        uses: actionshub/markdownlint@main
        with:
          filesToIgnore: |
            **/.build/**
            **/Pods/**
            **/Carthage/**
            **/.swiftpm/**
            **/DerivedData/**
            **/node_modules/**
            **/vendor/**
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --exclude "img.shields.io|starchart.cc" --verbose --no-progress "**/*.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
