name: Markdown Lint
on:
  pull_request:
    paths: ["**/*.md"]
  push:
    paths: ["**/*.md"]
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: |
            **/*.md
