name: Markdown Quality
on:
  pull_request:
    paths: ['**/*.md']
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i -g textlint @textlint/markdown textlint-rule-terminology textlint-rule-no-dead-link
      - run: |
          cat > .textlintrc.json <<'JSON'
          {
            "rules": {
              "terminology": true,
              "no-dead-link": { "checkRelative": true }
            }
          }
          JSON
      - run: textlint -f pretty-error '**/*.md'
